control: 
  model: stgcn
  testonly: true
  device: cuda:0
  mdir: ./results/model/
  logdir: ./results/log/
  date: 2023y04m02d

data:
  dataset: PEMS7
  val_ratio: 0.2
  test_ratio: 0.2
  lag: 12
  horizon: 12
  batch_size: 32
  geo_graph: ./data/county/geo_geaph_county_full.cpt
  num_nodes: 1481 
  pre_adj: true
  adj_th: 0.00001
  sigma: 100
  norm: max01

training:
  patience: 20
  model_path: ./results/model/2022y9m5d/STID.pkl
  mae_thresh: 0.0
  mape_thresh: 0.0
  lr: 0.002
  weight_decay: 0.0001
  # weight_decay: 0.0
  lr_decay_ratio: 0.5
  steps: [1, 50, 100]
  criterion: 'Smooth'
  max_epoch: 200
  grad_norm: true
  # debug: false
  t_s_mode: t

model:
# GIB
  end_channels: 128
  adj_type: normlap
  in_dim: 1
  out_dim: 12
  
sample:
  is_sample: False